// 50 популярних тегів для мемів у LinkedIn
export const MEME_TAGS = [
  '#TechHumor',
  '#DevLife',
  '#ProgrammerHumor',
  '#SoftwareEngineering',
  '#CodingLife',
  '#ITHumor',
  '#WorkFromHome',
  '#TechMemes',
  '#DeveloperLife',
  '#CodeNewbie',
  '#JavaScript',
  '#Python',
  '#WebDev',
  '#FullStack',
  '#StartupLife',
  '#ProductivityHacks',
  '#AgileLife',
  '#TechWorld',
  '#OfficeHumor',
  '#MondayMotivation',
  '#WorkLifeBalance',
  '#LinkedInHumor',
  '#CareerGrowth',
  '#TechIndustry',
  '#Debugging',
  '#CodeReview',
  '#StandupMeeting',
  '#DeadlineLife',
  '#RemoteWork',
  '#CloudComputing',
  '#AIHumor',
  '#MachineLearning',
  '#DataScience',
  '#CyberSecurity',
  '#DevOps',
  '#OpenSource',
  '#GitHub',
  '#TechLeadership',
  '#EngineeringCulture',
  '#TeamWork',
  '#Innovation',
  '#Entrepreneurship',
  '#TechStartup',
  '#ProductManagement',
  '#UXDesign',
  '#BackendDev',
  '#FrontendDev',
  '#MobileApp',
  '#SRELife',
  '#CleanCode',
];

// Повертає n унікальних рандомних тегів
export function pickRandomTags(n = 4) {
  const shuffled = [...MEME_TAGS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
